import { makeStyles, shorthands, tokens } from '@fluentui/react-components';

export const useAppStyles = makeStyles({
  page: {
    height: "100%",
    ...shorthands.padding("12px"),
    overflow: "hidden",
    boxSizing: "border-box",
    background: "var(--app-bg)",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    rowGap: "12px",
  },
  appTopBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "8px",
    ...shorthands.padding("8px", "12px"),
    borderRadius: tokens.borderRadiusMedium,
    border: "1px solid var(--panel-border)",
    backgroundColor: "var(--panel-bg)",
    boxShadow: "var(--panel-shadow)",
    backdropFilter: "blur(14px)",
  },
  layout: {
    height: "100%",
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "300px 1fr",
    gap: "12px",
  },
  card: {
    ...shorthands.padding("16px"),
    backgroundColor: "var(--panel-bg)",
    border: "1px solid var(--panel-border)",
    boxShadow: "var(--panel-shadow)",
    backdropFilter: "blur(14px)",
    minHeight: 0,
    overflow: "hidden",
  },
  sidebarCard: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    height: "100%",
    minHeight: 0,
  },
  sidebarContent: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    display: "grid",
    alignContent: "start",
    gap: "10px",
  },
  mainCard: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    height: "100%",
    minHeight: 0,
  },
  sidebarBottom: {
    display: "grid",
    gap: "8px",
    borderTop: "1px solid color-mix(in srgb, var(--panel-border) 60%, #7a8da8 40%)",
    marginTop: "auto",
    flexShrink: 0,
    ...shorthands.padding("6px", 0, 0, 0),
  },
  cardHead: {
    display: "inline-flex",
    alignItems: "center",
    columnGap: "8px",
    ...shorthands.padding("6px", "12px"),
    borderRadius: tokens.borderRadiusCircular,
    backgroundColor: "var(--head-pill-bg)",
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  createButtonRow: {
    display: "grid",
    gap: "6px",
  },
  fullWidthButton: {
    width: "100%",
    justifyContent: "center",
  },
  list: {
    margin: 0,
    ...shorthands.padding(0),
    listStyleType: "none",
    display: "grid",
    gap: "10px",
    alignContent: "start",
    overflowY: "auto",
    minHeight: 0,
  },
  instanceCard: {
    width: "100%",
    textAlign: "left",
    ...shorthands.padding("12px"),
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: "var(--item-bg)",
    border: "1px solid var(--item-border)",
    display: "grid",
    rowGap: "8px",
    cursor: "pointer",
    transitionDuration: "160ms",
    transitionProperty: "transform, box-shadow, border-color",
    boxShadow: "var(--item-shadow)",
    ":hover": {
      transform: "translateY(-1px)",
      boxShadow: "var(--item-shadow-hover)",
    },
  },
  instanceCardActive: {
    border: "1px solid var(--item-active-border)",
    boxShadow: "var(--item-active-shadow)",
  },
  instanceCardTitle: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    columnGap: "8px",
  },
  instanceNameText: {
    color: "var(--instance-title-color)",
  },
  tag: {
    ...shorthands.padding("2px", "8px"),
    borderRadius: tokens.borderRadiusCircular,
    fontSize: "12px",
    border: "1px solid var(--tag-border)",
    color: "var(--tag-color)",
    backgroundColor: "var(--tag-bg)",
  },
  empty: {
    color: tokens.colorNeutralForeground3,
  },
  status: {
    color: tokens.colorBrandForeground1,
  },
  mainTopBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "8px",
  },
  tabBar: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    flexWrap: "wrap",
  },
  tabButton: {
    minWidth: "120px",
  },
  mainDesc: {
    color: tokens.colorNeutralForeground3,
  },
  inlineForm: {
    display: "grid",
    gap: "14px",
  },
  addDialogSurface: {
    width: "min(760px, 92vw)",
  },
  detailDialogSurface: {
    width: "min(760px, 92vw)",
  },
  addDialogIntro: {
    color: tokens.colorNeutralForeground3,
    lineHeight: "1.5",
  },
  addDialogSection: {
    display: "grid",
    gap: "10px",
    ...shorthands.padding("12px"),
    borderRadius: tokens.borderRadiusMedium,
    border: "1px solid var(--item-border)",
    backgroundColor: "var(--item-bg)",
  },
  fieldGroup: {
    display: "grid",
    gap: "6px",
  },
  fieldHint: {
    color: tokens.colorNeutralForeground3,
    fontSize: "12px",
  },
  detailHeader: {
    display: "grid",
    gap: "4px",
  },
  dangerSection: {
    display: "grid",
    gap: "8px",
    ...shorthands.padding("12px"),
    borderRadius: tokens.borderRadiusMedium,
    border: "1px solid color-mix(in srgb, #d13438 45%, var(--item-border) 55%)",
    backgroundColor: "color-mix(in srgb, #d13438 10%, var(--item-bg) 90%)",
  },
  detailActionsLeft: {
    marginRight: "auto",
  },
  pathRow: {
    display: "grid",
    gridTemplateColumns: "1fr auto",
    gap: "8px",
    alignItems: "center",
  },
  componentPlaceholder: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "8px",
    borderRadius: tokens.borderRadiusMedium,
    border: "1px dashed var(--placeholder-border)",
    backgroundColor: "var(--placeholder-bg)",
    minHeight: 0,
    ...shorthands.padding("10px"),
  },
  optionsList: {
    display: "grid",
    alignContent: "start",
    gap: "12px",
    minHeight: 0,
    flex: 1,
    overflowY: "auto",
    ...shorthands.padding("4px"),
  },
  panelBody: {
    display: "grid",
    gap: "8px",
    minHeight: 0,
    flex: 1,
    alignContent: "start",
  },
  filterBar: {
    display: "grid",
    gridTemplateColumns: "minmax(220px, 1fr) minmax(160px, 220px) auto",
    gap: "10px",
    alignItems: "center",
  },
  optionCard: {
    display: "grid",
    gap: "6px",
    ...shorthands.padding("10px", "12px"),
    borderRadius: tokens.borderRadiusMedium,
    border: "1px solid var(--item-border)",
    backgroundColor: "var(--item-bg)",
  },
  compactInfoCard: {
    gap: "4px",
    ...shorthands.padding("12px"),
    minHeight: "unset",
  },
  activeOptionCard: {
    border: "1px solid var(--item-active-border)",
    boxShadow: "var(--item-active-shadow)",
  },
  footerBar: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: "8px",
    flexShrink: 0,
  },
  modalGrid: {
    display: "grid",
    gap: "10px",
  },
  danger: {
    color: tokens.colorPaletteRedForeground1,
  },
  itemFooter: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "10px",
  },
  rightAligned: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: "8px",
  },
  dialogSurface: {
    backgroundColor: "var(--panel-bg)",
    border: "1px solid var(--panel-border)",
    boxShadow: "var(--panel-shadow)",
    backdropFilter: "blur(14px)",
  },
  settingsDialogSurface: {
    width: "min(1080px, 94vw)",
    height: "min(680px, 86vh)",
    backgroundColor: "var(--panel-bg)",
    border: "1px solid var(--panel-border)",
    boxShadow: "var(--panel-shadow)",
    backdropFilter: "blur(14px)",
  },
  settingsDialogBody: {
    height: "100%",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr) auto",
    gap: "16px",
  },
  settingsDialogContent: {
    minHeight: 0,
    overflow: "hidden",
    backgroundColor: "transparent",
  },
  settingsLayout: {
    height: "100%",
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "180px minmax(0, 1fr)",
    gap: "20px",
  },
  settingsNav: {
    display: "grid",
    alignContent: "start",
    gap: "8px",
    ...shorthands.padding("14px"),
    borderRadius: tokens.borderRadiusLarge,
    border: "1px solid var(--item-border)",
    backgroundColor: "var(--item-bg)",
  },
  settingsNavButton: {
    width: "100%",
    justifyContent: "flex-start",
    minHeight: "38px",
  },
  settingsContent: {
    minHeight: 0,
    overflowY: "auto",
    display: "grid",
    alignContent: "start",
    gap: "16px",
    ...shorthands.padding("4px", "10px", "4px", "4px"),
  },
  settingsPageHeader: {
    display: "grid",
    gap: "4px",
    ...shorthands.padding("4px", "2px", "10px"),
    borderBottom: "1px solid var(--panel-border)",
  },
  settingsEyebrow: {
    color: tokens.colorBrandForeground1,
    fontSize: "11px",
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
  },
  settingsTitle: {
    fontSize: "22px",
    fontWeight: 700,
  },
  settingsLead: {
    color: tokens.colorNeutralForeground3,
    lineHeight: "1.5",
  },
  settingsSection: {
    display: "grid",
    gap: "10px",
    ...shorthands.padding("16px"),
    borderRadius: tokens.borderRadiusLarge,
    border: "1px solid var(--item-border)",
    backgroundColor: "var(--item-bg)",
  },
  aboutHero: {
    display: "grid",
    gap: "8px",
    ...shorthands.padding("22px"),
    borderRadius: tokens.borderRadiusLarge,
    color: tokens.colorNeutralForegroundOnBrand,
    background: "linear-gradient(135deg, #0d5b7a 0%, #147a8e 48%, #2d9d8f 100%)",
  },
  aboutName: {
    fontSize: "28px",
    fontWeight: 700,
    letterSpacing: "-0.03em",
  },
  aboutVersion: {
    width: "fit-content",
    ...shorthands.padding("3px", "9px"),
    borderRadius: tokens.borderRadiusCircular,
    backgroundColor: "rgba(255, 255, 255, 0.18)",
    fontSize: "12px",
  },
  aboutLinkGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: "12px",
  },
  aboutLinkCard: {
    display: "grid",
    gap: "4px",
    ...shorthands.padding("14px"),
    borderRadius: tokens.borderRadiusMedium,
    border: "1px solid var(--item-border)",
    backgroundColor: "var(--item-bg)",
  },
  aboutLink: {
    color: tokens.colorBrandForegroundLink,
    fontWeight: 600,
    overflowWrap: "anywhere",
  },
  dialogContent: {
    backgroundColor: "transparent",
  },
  contextTitle: {
    fontWeight: 600,
  },
});


