import { makeStyles, shorthands, tokens } from '@fluentui/react-components';

export const useAppStyles = makeStyles({
  page: {
    height: "100%",
    ...shorthands.padding("12px"),
    overflow: "hidden",
    boxSizing: "border-box",
    background: "var(--app-bg)",
    display: "grid",
    gridTemplateRows: "auto minmax(0, 1fr)",
    rowGap: "12px",
  },
  appTopBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "8px",
    ...shorthands.padding("8px", "12px"),
    borderRadius: tokens.borderRadiusMedium,
    border: "1px solid var(--panel-border)",
    backgroundColor: "var(--panel-bg)",
    boxShadow: "var(--panel-shadow)",
    backdropFilter: "blur(14px)",
  },
  layout: {
    height: "100%",
    minHeight: 0,
    display: "grid",
    gridTemplateColumns: "300px 1fr",
    gap: "12px",
  },
  card: {
    ...shorthands.padding("16px"),
    backgroundColor: "var(--panel-bg)",
    border: "1px solid var(--panel-border)",
    boxShadow: "var(--panel-shadow)",
    backdropFilter: "blur(14px)",
    minHeight: 0,
    overflow: "hidden",
  },
  sidebarCard: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    height: "100%",
    minHeight: 0,
  },
  sidebarContent: {
    flex: 1,
    minHeight: 0,
    overflow: "auto",
    display: "grid",
    alignContent: "start",
    gap: "10px",
  },
  mainCard: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    height: "100%",
    minHeight: 0,
  },
  sidebarBottom: {
    display: "grid",
    gap: "8px",
    borderTop: "1px solid color-mix(in srgb, var(--panel-border) 60%, #7a8da8 40%)",
    marginTop: "auto",
    flexShrink: 0,
    ...shorthands.padding("6px", 0, 0, 0),
  },
  cardHead: {
    display: "inline-flex",
    alignItems: "center",
    columnGap: "8px",
    ...shorthands.padding("6px", "12px"),
    borderRadius: tokens.borderRadiusCircular,
    backgroundColor: "var(--head-pill-bg)",
  },
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  createButtonRow: {
    display: "grid",
    gap: "6px",
  },
  fullWidthButton: {
    width: "100%",
    justifyContent: "center",
  },
  list: {
    margin: 0,
    ...shorthands.padding(0),
    listStyleType: "none",
    display: "grid",
    gap: "10px",
    alignContent: "start",
    overflowY: "auto",
    minHeight: 0,
  },
  instanceCard: {
    width: "100%",
    textAlign: "left",
    ...shorthands.padding("12px"),
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: "var(--item-bg)",
    border: "1px solid var(--item-border)",
    display: "grid",
    rowGap: "8px",
    cursor: "pointer",
    transitionDuration: "160ms",
    transitionProperty: "transform, box-shadow, border-color",
    boxShadow: "var(--item-shadow)",
    ":hover": {
      transform: "translateY(-1px)",
      boxShadow: "var(--item-shadow-hover)",
    },
  },
  instanceCardActive: {
    border: "1px solid var(--item-active-border)",
    boxShadow: "var(--item-active-shadow)",
  },
  instanceCardTitle: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    columnGap: "8px",
  },
  instanceNameText: {
    color: "var(--instance-title-color)",
  },
  tag: {
    ...shorthands.padding("2px", "8px"),
    borderRadius: tokens.borderRadiusCircular,
    fontSize: "12px",
    border: "1px solid var(--tag-border)",
    color: "var(--tag-color)",
    backgroundColor: "var(--tag-bg)",
  },
  empty: {
    color: tokens.colorNeutralForeground3,
  },
  status: {
    color: tokens.colorBrandForeground1,
  },
  mainTopBar: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "8px",
  },
  mainDesc: {
    color: tokens.colorNeutralForeground3,
  },
  inlineForm: {
    display: "grid",
    gap: "14px",
  },
  addDialogSurface: {
    width: "min(760px, 92vw)",
  },
  detailDialogSurface: {
    width: "min(760px, 92vw)",
  },
  addDialogIntro: {
    color: tokens.colorNeutralForeground3,
    lineHeight: "1.5",
  },
  addDialogSection: {
    display: "grid",
    gap: "10px",
    ...shorthands.padding("12px"),
    borderRadius: tokens.borderRadiusMedium,
    border: "1px solid var(--item-border)",
    backgroundColor: "var(--item-bg)",
  },
  fieldGroup: {
    display: "grid",
    gap: "6px",
  },
  fieldHint: {
    color: tokens.colorNeutralForeground3,
    fontSize: "12px",
  },
  detailHeader: {
    display: "grid",
    gap: "4px",
  },
  dangerSection: {
    display: "grid",
    gap: "8px",
    ...shorthands.padding("12px"),
    borderRadius: tokens.borderRadiusMedium,
    border: "1px solid color-mix(in srgb, #d13438 45%, var(--item-border) 55%)",
    backgroundColor: "color-mix(in srgb, #d13438 10%, var(--item-bg) 90%)",
  },
  detailActionsLeft: {
    marginRight: "auto",
  },
  pathRow: {
    display: "grid",
    gridTemplateColumns: "1fr auto",
    gap: "8px",
    alignItems: "center",
  },
  componentPlaceholder: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    borderRadius: tokens.borderRadiusMedium,
    border: "1px dashed var(--placeholder-border)",
    backgroundColor: "var(--placeholder-bg)",
    minHeight: 0,
    ...shorthands.padding("10px"),
  },
  optionsList: {
    display: "grid",
    alignContent: "start",
    gap: "12px",
    minHeight: 0,
    flex: 1,
    overflowY: "auto",
    ...shorthands.padding("4px"),
  },
  optionCard: {
    display: "grid",
    gap: "6px",
    ...shorthands.padding("10px", "12px"),
    borderRadius: tokens.borderRadiusMedium,
    border: "1px solid var(--item-border)",
    backgroundColor: "var(--item-bg)",
  },
  footerBar: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: "8px",
    flexShrink: 0,
  },
  modalGrid: {
    display: "grid",
    gap: "10px",
  },
  danger: {
    color: tokens.colorPaletteRedForeground1,
  },
  itemFooter: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: "10px",
  },
  rightAligned: {
    display: "flex",
    justifyContent: "flex-end",
    alignItems: "center",
    gap: "8px",
  },
  dialogSurface: {
    backgroundColor: "var(--panel-bg)",
    border: "1px solid var(--panel-border)",
    boxShadow: "var(--panel-shadow)",
    backdropFilter: "blur(14px)",
  },
  dialogContent: {
    backgroundColor: "transparent",
  },
  contextTitle: {
    fontWeight: 600,
  },
});


